### ISSUE TITLE
'Derive Code List based on this' button does not work

### ISSUE THREAD

**Issue by elenajelisic** [OAGi/Score#1340]
1. The EU is searching for the oacl_CurrencyCode Code List

![image](https://user-images.githubusercontent.com/103444540/195105118-9434940b-9a38-4468-86c3-e2603372e7fd.png)

2. The EU clicks on the button 'Derive Code List based on this'

![image](https://user-images.githubusercontent.com/103444540/195106605-ca734840-d2d3-4dd2-b22b-767da2327f3e.png)

3. On the back-end the following error is shown:

`java.sql.SQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`oagi`.`code_list`, CONSTRAINT `code_list_agency_id_list_value_id_fk` FOREIGN KEY (`agency_id_list_value_id`) REFERENCES `agency_id_list_value` (`agency_id_list_value_id`))
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariCP-4.0.3.jar:na]
	at org.jooq.tools.jdbc.DefaultPreparedStatement.executeUpdate(DefaultPreparedStatement.java:109) ~[jooq-3.17.4.jar:na]
	at org.jooq.impl.AbstractDMLQuery.executeReturningGeneratedKeysFetchAdditionalRows(AbstractDMLQuery.java:1230) ~[jooq-3.17.4.jar:na]
	at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:1060) ~[jooq-3.17.4.jar:na]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:341) ~[jooq-3.17.4.jar:na]
	at org.jooq.impl.DMLQueryAsResultQuery.fetch(DMLQueryAsResultQuery.java:144) ~[jooq-3.17.4.jar:na]
	at org.jooq.impl.ResultQueryTrait.fetchLazy(ResultQueryTrait.java:281) ~[jooq-3.17.4.jar:na]
	at org.jooq.impl.ResultQueryTrait.fetchLazyNonAutoClosing(ResultQueryTrait.java:290) ~[jooq-3.17.4.jar:na]
	at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:509) ~[jooq-3.17.4.jar:na]`

**Comment by hakjuoh** [comment]
@elenajelisic This issue is associated with #1330. Previously, `code_list` table directly points to `agency_id_list_value_id` table, but it replaced with `code_list_manifest`.`agency_id_list_value_manifest_id`.

**Comment by elenajelisic** [comment]
@hakjuoh It works now.
