### ISSUE TITLE
For EU CCs, an EU cannot add BBIE to previously created Top-level ASBIEP.

### ISSUE THREAD

**Issue by elena-jelisic** [OAGi/Score#1594]
1. An EU creates a new BCCP, named "New_BCCP".

![Screenshot 2024-01-08 at 12 31 17 PM](https://github.com/OAGi/Score/assets/71283987/7ad3f680-243f-46a8-bec5-04617ebf9515)

2. An EU changes the state of the newly created BCCP to 'Production'.

![Screenshot 2024-01-08 at 12 33 38 PM](https://github.com/OAGi/Score/assets/71283987/363fde8b-9f6b-43cf-9852-2e9b9e4e4067)

3. An EU creates a new ACC, named "New_ACC", appends previously created BCCP and changes the state of the ACC to 'Production'.

![Screenshot 2024-01-08 at 12 36 05 PM](https://github.com/OAGi/Score/assets/71283987/7645debf-2739-4769-924a-e889cfbbc19a)

4. An EU creates a new ASCCP for previously created ACC, also in the 'Production' state.
5. An EU creates new BIE for previously created ASCCP.
6. When an EU selects the check box next to the "New_BCCP" and tries to Update the BIE the following error message is displayed:

![Screenshot 2024-01-08 at 12 42 59 PM](https://github.com/OAGi/Score/assets/71283987/20d110a2-df8e-4461-8151-4b63476d35cd)

7. At the back-end the following exception is thrown.

```java
java.lang.IllegalArgumentException: null
	at org.oagi.score.repo.component.bbie.BbieWriteRepository.upsertBbie(BbieWriteRepository.java:153) ~[classes/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:352) ~[spring-aop-6.1.1.jar:6.1.1]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.1.1.jar:6.1.1]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.1.1.jar:6.1.1]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.1.jar:6.1.1]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-6.1.1.jar:6.1.1]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.1.1.jar:6.1.1]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.1.jar:6.1.1]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717) ~[spring-aop-6.1.1.jar:6.1.1]
	at org.oagi.score.repo.component.bbie.BbieWriteRepository$$SpringCGLIB$$0.upsertBbie(<generated>) ~[classes/:na]
	at org.oagi.score.gateway.http.api.bie_management.service.BieEditService.lambda$updateDetails$11(BieEditService.java:368) ~[classes/:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[na:na]
	at org.oagi.score.gateway.http.api.bie_management.service.BieEditService.updateDetails(BieEditService.java:372) ~[classes/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:352) ~[spring-aop-6.1.1.jar:6.1.1]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.1.1.jar:6.1.1]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.1.1.jar:6.1.1]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.1.jar:6.1.1]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-6.1.1.jar:6.1.1]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:385) ~[spring-tx-6.1.1.jar:6.1.1]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-6.1.1.jar:6.1.1]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.1.1.jar:6.1.1]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.1.jar:6.1.1]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717) ~[spring-aop-6.1.1.jar:6.1.1]
	at org.oagi.score.gateway.http.api.bie_management.service.BieEditService$$SpringCGLIB$$0.updateDetails(<generated>) ~[classes/:na]
	at org.oagi.score.gateway.http.api.bie_management.controller.BieEditController.updateDetails(BieEditController.java:217) ~[classes/:na]
``` 
8. When an EU tries to click on the "New_BCCP" node, the following message is displayed:

![Screenshot 2024-01-08 at 12 48 14 PM](https://github.com/OAGi/Score/assets/71283987/9b4afa3b-9a67-445d-a238-8b278822f4f5)

9. At the back-end the following exception is thrown.

```java
java.lang.NullPointerException: Cannot invoke "org.oagi.score.data.BdtPriRestri.getCodeListManifestId()" because "defaultBdtPriRestri" is null
	at org.oagi.score.repo.component.bbie.BbieReadRepository.getBbieNode(BbieReadRepository.java:101) ~[classes/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:352) ~[spring-aop-6.1.1.jar:6.1.1]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.1.1.jar:6.1.1]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.1.1.jar:6.1.1]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.1.jar:6.1.1]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-6.1.1.jar:6.1.1]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.1.1.jar:6.1.1]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.1.jar:6.1.1]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717) ~[spring-aop-6.1.1.jar:6.1.1]
	at org.oagi.score.repo.component.bbie.BbieReadRepository$$SpringCGLIB$$0.getBbieNode(<generated>) ~[classes/:na]
	at org.oagi.score.gateway.http.api.bie_management.service.BieEditService.getBbieDetail(BieEditService.java:504) ~[classes/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:352) ~[spring-aop-6.1.1.jar:6.1.1]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.1.1.jar:6.1.1]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.1.1.jar:6.1.1]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.1.jar:6.1.1]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-6.1.1.jar:6.1.1]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:385) ~[spring-tx-6.1.1.jar:6.1.1]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-6.1.1.jar:6.1.1]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.1.1.jar:6.1.1]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.1.jar:6.1.1]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717) ~[spring-aop-6.1.1.jar:6.1.1]
	at org.oagi.score.gateway.http.api.bie_management.service.BieEditService$$SpringCGLIB$$0.getBbieDetail(<generated>) ~[classes/:na]
	at org.oagi.score.gateway.http.api.bie_management.controller.BieEditController.getBbieDetail(BieEditController.java:84) ~[classes/:na]
```

**Comment by hakjuoh** [comment]
@elena-jelisic The reason for the error was that users could select a CDT (Numeric Type) for a new BCCP. I made a change so that no CDTs will show up in the dialog for creating BCCPs (See [commit](https://github.com/OAGi/Score/commit/c85f2bca9c67918607cc0bea6f3c4af9d6507310)).

**Comment by elena-jelisic** [comment]
@hakjuoh It works okay.
